version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
          pip install -e .
          pip install '.[test]'
          pytest
          name: Install and test Flask blog app
workflows:
  main:
    jobs:
      - build-and-test
