version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-test-and-deploy:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Flask blog app
          command: pip install -e . && pip install '.[test]'
      - run:
          name: Test Flask blog app
          command: pytest
      - run:
          name: Deploy to Dockerhub
          command: |
          if [ "${CIRCLE_BRANCH}" == "main" ]; then
           docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
           docker build -t ${DOCKER_USER}/${DOCKER_REPONAME}:latest .;
           docker push ${DOCKER_USER}/${DOCKER_REPONAME}:latest;
         fi

workflows:
  main:
    jobs:
      - build-test-and-deploy
